/*Populate tabla clientes*/
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('79514933','chikitina preciosa', 'negrito esclavo', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('12121234','eusebio maria', 'amazonas tumaco', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('678976379','gulupa tomate', 'papaya chontaduro', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('54545453','chonto perol1', 'papaya chontaduro', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('12312345','bocadillo santurron', 'papaya chontaduro', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('79514932','chikitina preciosa', 'negrito esclavo', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('12121299','eusebio maria', 'amazonas tumaco', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('678976354','gulupa maraciya', 'papaya chontaduro', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('545454','chonto perol2', 'papaya chontaduro', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('79514930','chikitina hemosa', 'negrito esclavo', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('12121211','eusebio tortuga', 'amazonas tumaco', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('678976384','gulupa guayaba', 'papaya chontaduro', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
insert into clientes(id_cliente, nombres, apellidos, direccion,municipio,departamento,telefono,email,sexo,edad,caracteristicas,fecha_Creacion) values ('54545445','chonto perol3', 'papaya chontaduro', 'avendida nore carrera sur', 'cordoba','antioquia', '3102345678', 'chikis@gmail.com', 'F', 33,'dolor cabeza', '13-01-1989');
